apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::757502562662:role/github-actions-role
    username: github-actions-role
    groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::757502562662:user/github_ci
      username: github_ci
      groups:
        - system:masters